# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: uni.edu
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - 127.0.0.1
      - Hostname: orderer3
        SANS:
          - 127.0.0.1
      - Hostname: orderer4
        SANS:
          - 127.0.0.1
      - Hostname: orderer5
        SANS:
          - 127.0.0.1

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Students
    Domain: students.uni.edu
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - 127.0.0.1
    Users:
      Count: 1

  - Name: Admins
    Domain: admins.uni.edu
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - 127.0.0.1
    Users:
      Count: 1

  - Name: Professors
    Domain: professors.uni.edu
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - 127.0.0.1
    Users:
      Count: 1
